


kind: pipeline
type: docker
name: SportSpotsPipeLine

trigger:
  branch:
    - master
  event:
    - push


steps:
  - name : FirstBuild
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - cd SportSpots
      - dotnet restore SportSpots.sln
      - dotnet build SportSpots.sln -c Release --no-restore

      secrets: [ SportsSpotsSecret ]
    
