


kind: pipeline
type: docker
name: SportSpotsPipeLine

trigger:
  branch:
    - master
  event:
    - push


steps:
  - name : FirstBuild
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet7-maui
    commands:
      - cd SportSpots
      - dotnet restore SportSpots.sln
      - dotnet build SportSpots.sln -c Release --no-restore

      secrets: [ SportsSpotsSecret ]
    
